name: click_workers
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.3.1
  material_duration_picker: ^0.1.1
  provider: ^6.1.5
  rxdart: ^0.27.7
  image_picker: ^1.1.2
  http: ^1.5.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  table_calendar: ^3.2.0
  file_picker: ^8.0.7
  dotted_border: ^3.1.0
  flutter_multi_formatter: ^2.13.10
  go_router: ^17.1.0
  youtube_player_iframe: ^5.1.3
  google_fonts: ^8.0.2
  flutter_secure_storage: ^9.2.4
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/googlelogo.png
    - assets/auth/logo.png
    - assets/auth/verify.png
    - assets/auth/reset_password.png
    - assets/social_media.gif
    - assets/profile_plus.png
    - assets/choose.png
    - assets/atm_card.png
    - assets/earn.png
    - assets/first_place.png
    - assets/game.png
    - assets/chart.png
    - assets/treasure.png
    - assets/treasur.png
    - assets/treasure_anim.gif
    - assets/spin.png
    - assets/referral.png
    - assets/logo_icon.png
    - assets/X.png
    - assets/Facebook.png
    - assets/instagram.png
    - assets/Youtube.png
    - assets/LinkedIn.png
    - assets/whatsapp.png
    - assets/telegram.png
    - assets/insta.png
    - assets/snap.png
    - assets/tiktok.png
    - assets/icons/
    - assets/rewards/
    - assets/wallets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 500
          style: italic
