"""initial schema

Revision ID: 8797888211ed
Revises: 
Create Date: 2026-08-29 14:52:57.174303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8797888211ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referred_by', sa.UUID(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_provider_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_provider_id'), 'users', ['oauth_provider_id'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('tni_service_type', sa.String(length=30), nullable=False),
    sa.Column('cw_task_category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('client_budget_kobo', sa.Integer(), nullable=False),
    sa.Column('client_price_per_action_kobo', sa.Integer(), nullable=False),
    sa.Column('worker_pay_per_action_kobo', sa.Integer(), nullable=False),
    sa.Column('escrow_kobo', sa.Integer(), nullable=False),
    sa.Column('slots_total', sa.Integer(), nullable=False),
    sa.Column('slots_filled', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('has_targeting', sa.Boolean(), nullable=False),
    sa.Column('has_instructions', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('comment_subtype', sa.String(length=50), nullable=True),
    sa.Column('video_subtype', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_owner_id'), 'campaigns', ['owner_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('kyc_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_bracket', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('ethnicity_tribe', sa.String(length=100), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('languages_spoken', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('primary_city', sa.String(length=100), nullable=True),
    sa.Column('primary_state', sa.String(length=100), nullable=True),
    sa.Column('primary_country', sa.String(length=100), nullable=True),
    sa.Column('secondary_locations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('occupation_location', sa.String(length=100), nullable=True),
    sa.Column('state_of_origin', sa.String(length=100), nullable=True),
    sa.Column('town_of_origin', sa.String(length=100), nullable=True),
    sa.Column('monthly_income_range', sa.String(length=50), nullable=True),
    sa.Column('primary_income_source', sa.String(length=100), nullable=True),
    sa.Column('secondary_income_source', sa.String(length=100), nullable=True),
    sa.Column('occupation_industry', sa.String(length=100), nullable=True),
    sa.Column('is_self_employed', sa.Boolean(), nullable=False),
    sa.Column('self_employed_industry', sa.String(length=100), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('department_of_study', sa.String(length=100), nullable=True),
    sa.Column('study_location', sa.String(length=100), nullable=True),
    sa.Column('trade_school_niche', sa.String(length=100), nullable=True),
    sa.Column('interests_hobbies', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('music_genres', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('content_niches_posted', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('content_types_interacted', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('account_types_followed', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('avg_story_views', sa.Integer(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('posting_frequency', sa.String(length=50), nullable=True),
    sa.Column('majority_follower_location', sa.String(length=100), nullable=True),
    sa.Column('follower_categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('follower_industries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('follower_care_about', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('account_age_years', sa.Float(), nullable=True),
    sa.Column('is_verified_on_platform', sa.Boolean(), nullable=False),
    sa.Column('uses_real_name', sa.Boolean(), nullable=False),
    sa.Column('uses_real_photo', sa.Boolean(), nullable=False),
    sa.Column('group_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('group_industries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('group_descriptions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('gender_group_membership', sa.String(length=30), nullable=True),
    sa.Column('marital_group_keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('tiktok_handle', sa.String(length=100), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('facebook_handle', sa.String(length=100), nullable=True),
    sa.Column('youtube_handle', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('leaderboard_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('avg_speed_minutes', sa.Float(), nullable=False),
    sa.Column('avg_client_rating', sa.Float(), nullable=False),
    sa.Column('tasks_approved', sa.Integer(), nullable=False),
    sa.Column('tasks_rejected', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('cat_one_off_single', sa.Integer(), nullable=False),
    sa.Column('cat_one_off_grouped', sa.Integer(), nullable=False),
    sa.Column('cat_repeating_single', sa.Integer(), nullable=False),
    sa.Column('cat_repeating_grouped', sa.Integer(), nullable=False),
    sa.Column('cat_trend_push', sa.Integer(), nullable=False),
    sa.Column('cat_skill_based', sa.Integer(), nullable=False),
    sa.Column('cat_unpaid', sa.Integer(), nullable=False),
    sa.Column('ts_score', sa.Float(), nullable=False),
    sa.Column('cr_score', sa.Float(), nullable=False),
    sa.Column('ar_score', sa.Float(), nullable=False),
    sa.Column('tq_score', sa.Float(), nullable=False),
    sa.Column('td_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_scores_worker_id'), 'leaderboard_scores', ['worker_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance_kobo', sa.Integer(), nullable=False),
    sa.Column('escrow_kobo', sa.Integer(), nullable=False),
    sa.Column('click_points', sa.Integer(), nullable=False),
    sa.Column('total_earned_kobo', sa.Integer(), nullable=False),
    sa.Column('total_withdrawn_kobo', sa.Integer(), nullable=False),
    sa.Column('total_spent_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_one_off_single_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_one_off_grouped_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_repeating_single_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_repeating_grouped_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_trend_push_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_skill_based_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_unpaid_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(), nullable=True),
    sa.Column('total_one_off_single_kobo', sa.Integer(), nullable=False),
    sa.Column('total_one_off_grouped_kobo', sa.Integer(), nullable=False),
    sa.Column('total_repeating_single_kobo', sa.Integer(), nullable=False),
    sa.Column('total_repeating_grouped_kobo', sa.Integer(), nullable=False),
    sa.Column('total_trend_push_kobo', sa.Integer(), nullable=False),
    sa.Column('total_skill_based_kobo', sa.Integer(), nullable=False),
    sa.Column('total_unpaid_kobo', sa.Integer(), nullable=False),
    sa.Column('daily_one_off_single_cps', sa.Integer(), nullable=False),
    sa.Column('daily_one_off_grouped_cps', sa.Integer(), nullable=False),
    sa.Column('daily_repeating_single_cps', sa.Integer(), nullable=False),
    sa.Column('daily_repeating_grouped_cps', sa.Integer(), nullable=False),
    sa.Column('daily_trend_push_cps', sa.Integer(), nullable=False),
    sa.Column('daily_skill_based_cps', sa.Integer(), nullable=False),
    sa.Column('daily_unpaid_cps', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('campaign_targeting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('target_genders', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_age_brackets', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_marital_statuses', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_income_ranges', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_religions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_ethnicities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_races', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_cities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_states', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_countries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_industries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_interests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('min_follower_count', sa.Integer(), nullable=False),
    sa.Column('min_avg_story_views', sa.Integer(), nullable=False),
    sa.Column('current_expansion_tier', sa.Integer(), nullable=False),
    sa.Column('last_expanded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('task_allocation_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('action_label', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('slots_allocated', sa.Integer(), nullable=False),
    sa.Column('slots_filled', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('task_category', sa.String(length=40), nullable=True),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('click_points_awarded', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('allocation_group_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('cw_task_category', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('is_high_earning', sa.Boolean(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('is_midnight', sa.Boolean(), nullable=False),
    sa.Column('pay_kobo', sa.Integer(), nullable=False),
    sa.Column('click_points_base', sa.Integer(), nullable=False),
    sa.Column('slots_total', sa.Integer(), nullable=False),
    sa.Column('slots_filled', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accept_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_group_id'], ['task_allocation_groups.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_campaign_id'), 'tasks', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('task_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_acceptances_task_id'), 'task_acceptances', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_acceptances_worker_id'), 'task_acceptances', ['worker_id'], unique=False)
    op.create_table('task_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cp_reward_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('acceptance_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proof_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('proof_link', sa.String(length=500), nullable=True),
    sa.Column('proof_image_hash', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('query_reason', sa.Text(), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('client_rating', sa.Float(), nullable=True),
    sa.Column('task_speed_minutes', sa.Float(), nullable=True),
    sa.Column('was_auto_approved', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acceptance_id'], ['task_acceptances.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_submissions_worker_id'), 'submissions', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_worker_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('task_reports')
    op.drop_index(op.f('ix_task_acceptances_worker_id'), table_name='task_acceptances')
    op.drop_index(op.f('ix_task_acceptances_task_id'), table_name='task_acceptances')
    op.drop_table('task_acceptances')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_campaign_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('task_allocation_groups')
    op.drop_table('campaign_targeting')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_leaderboard_scores_worker_id'), table_name='leaderboard_scores')
    op.drop_table('leaderboard_scores')
    op.drop_table('kyc_profiles')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_owner_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
