"""add notifications, reward claims, wallet gamification columns

Revision ID: ef457339320b
Revises: 8797888211ed
Create Date: 2026-08-29 19:54:25.406802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef457339320b'
down_revision: Union[str, None] = '8797888211ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reward_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reward_key', sa.String(length=60), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_claims_reward_key'), 'reward_claims', ['reward_key'], unique=False)
    op.create_index(op.f('ix_reward_claims_user_id'), 'reward_claims', ['user_id'], unique=False)
    op.add_column('wallets', sa.Column('last_spin_at', sa.DateTime(), nullable=True))
    op.add_column('wallets', sa.Column('last_checkin_at', sa.DateTime(), nullable=True))
    # server_default backfills existing rows (autogenerate omits this and
    # fails on any table that already has data — adjusted by hand).
    op.add_column('wallets', sa.Column('checkin_streak', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('wallets', 'checkin_streak', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'checkin_streak')
    op.drop_column('wallets', 'last_checkin_at')
    op.drop_column('wallets', 'last_spin_at')
    op.drop_index(op.f('ix_reward_claims_user_id'), table_name='reward_claims')
    op.drop_index(op.f('ix_reward_claims_reward_key'), table_name='reward_claims')
    op.drop_table('reward_claims')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
